# Generated by Django 4.2 on 2023-06-22 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# core.migrations.0018_initialize_slugs
# core.migrations.0020_auto_20230609_1847
# core.migrations.0022_initialize_slug_full


def initialize_slug(apps, schema_editor):
    Article = apps.get_model("core", "Article")
    for article in Article.objects.all():
        article.slug = slugify(article.title)
        article.save()


def initialize_slug_section(apps, schema_editor):
    Article = apps.get_model("core", "Article")
    for article in Article.objects.all():
        article.slug_section = slugify(article.title)
        article.save()


from core.models import Article


def initialize_slug_full(apps, schema_editor):
    """Initialize slug_full field by looping through ancestors."""
    for article in Article.objects.all():
        slugs = []
        for ancestor in article.get_ancestors():
            slugs.append(ancestor.slug_section)
        slugs.append(article.slug_section)
        article.slug_full = "/".join(slugs)
        article.save()


class Migration(migrations.Migration):
    replaces = [
        ("core", "0001_initial"),
        ("core", "0002_articlemp"),
        ("core", "0003_alter_articlemp_article_html_and_more"),
        ("core", "0004_alter_articlemp_article_json_and_more"),
        ("core", "0005_remove_articlemp_is_published"),
        ("core", "0006_alter_annotation_article_alter_comment_article"),
        ("core", "0007_articlemp_author"),
        ("core", "0008_annotation_is_public"),
        ("core", "0009_delete_article"),
        ("core", "0010_rename_articlemp_article"),
        ("core", "0011_annotation_highlight_serialized"),
        ("core", "0012_rename_highlight_serialized_annotation_highlight_serialization"),
        ("core", "0013_remove_annotation_highlight_serialization"),
        ("core", "0014_alter_comment_created_on"),
        ("core", "0015_alter_comment_created_on"),
        ("core", "0016_alter_comment_created_on"),
        ("core", "0017_article_slug"),
        ("core", "0018_initialize_slugs"),
        ("core", "0019_remove_article_slug_article_slug_section"),
        ("core", "0020_auto_20230609_1847"),
        ("core", "0021_article_slug_full_alter_article_slug_section"),
        ("core", "0022_initialize_slug_full"),
        ("core", "0023_alter_article_slug_full"),
        ("core", "0024_alter_article_slug_full"),
        ("core", "0025_article_hidden"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=1000)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "article_html",
                    models.TextField(
                        blank=True, help_text="HTML output from WYSIWYG editor."
                    ),
                ),
                (
                    "article_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON output specific to ProseMirror.",
                        null=True,
                    ),
                ),
                (
                    "article_text",
                    models.TextField(
                        blank=True, help_text="Text output from WYSIWYG editor."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=100)),
                ("slug", models.SlugField(blank=True, default="")),
                ("hidden", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("highlight_start", models.PositiveIntegerField()),
                ("highlight_end", models.PositiveIntegerField()),
                ("highlight_backward", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.article"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("created_on", models.DateTimeField(auto_now=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "comment_html",
                    models.TextField(
                        blank=True, help_text="HTML output from rich-text editor."
                    ),
                ),
                (
                    "comment_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON output from rich-text editor.",
                        null=True,
                    ),
                ),
                (
                    "comment_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Plain-text output from rich-text editor.",
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.annotation",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.article"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(
            code=initialize_slug,
        ),
        migrations.RemoveField(
            model_name="article",
            name="slug",
        ),
        migrations.AddField(
            model_name="article",
            name="slug_section",
            field=models.SlugField(default=""),
        ),
        migrations.RunPython(
            code=initialize_slug_section,
        ),
        migrations.AddField(
            model_name="article",
            name="slug_full",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_section",
            field=models.TextField(max_length=50),
        ),
        migrations.RunPython(
            code=initialize_slug_full,
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_full",
            field=models.TextField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_full",
            field=models.TextField(db_index=True, max_length=1000, unique=True),
        ),
    ]
