# Generated by Django 4.1.7 on 2023-03-21 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotation",
            old_name="highlight_backwards",
            new_name="highlight_backward",
        ),
    ]
