# Generated by Django 4.1.7 on 2023-03-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="highlight",
            field=models.JSONField(help_text="JSON serialized range by Rangy library"),
        ),
    ]
