# Generated by Django 4.1.7 on 2023-04-02 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_rename_highlight_backwards_annotation_highlight_backward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
