# Generated by Django 4.2 on 2023-05-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_articlemp_article_html_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlemp",
            name="article_json",
            field=models.JSONField(
                blank=True, help_text="JSON output specific to ProseMirror.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="articlemp",
            name="article_text",
            field=models.TextField(
                blank=True, help_text="Text output from WYSIWYG editor."
            ),
        ),
    ]
