# Generated by Django 4.2 on 2023-05-03 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_articlemp_article_json_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articlemp",
            name="is_published",
        ),
    ]
