# Generated by Django 4.2 on 2023-04-13 17:29

from django.db import migrations


def transfer_comments(apps, schema_editor):
    Annotation = apps.get_model("core", "Annotation")
    Comment = apps.get_model("core", "Comment")

    for annotation in Annotation.objects.all():
        Comment.objects.create(
            user=annotation.user,
            annotation=annotation,
            reply_to=None,
            created_on=annotation.created_on,
            updated_on=annotation.updated_on,
            comment_html=annotation.comment_html,
            comment_json=annotation.comment_json,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_comment"),
    ]

    operations = [
        migrations.RunPython(transfer_comments),
    ]
