# Generated by Django 4.2 on 2023-04-13 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_migrate_comment_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotation",
            name="comment_html",
        ),
        migrations.RemoveField(
            model_name="annotation",
            name="comment_json",
        ),
        migrations.RemoveField(
            model_name="annotation",
            name="is_public",
        ),
    ]
