# Generated by Django 4.2 on 2023-05-05 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_articlemp_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.articlemp"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.articlemp"
            ),
        ),
    ]
