# Generated by Django 4.2 on 2023-04-14 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_remove_annotation_comment_html_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.annotation",
            ),
        ),
        migrations.CreateModel(
            name="CommentTree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "comment_html",
                    models.TextField(
                        blank=True, help_text="HTML output from rich-text editor."
                    ),
                ),
                (
                    "comment_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON output from rich-text editor.",
                        null=True,
                    ),
                ),
                (
                    "comment_text",
                    models.TextField(
                        blank=True,
                        help_text="Plain-text output from rich-text editor.",
                        null=True,
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_tree",
                        to="core.annotation",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.article"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
