# Generated by Django 4.2 on 2023-05-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_articlemp_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
