# Generated by Django 4.2 on 2023-05-15 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_annotation_is_public"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Article",
        ),
    ]
