# Generated by Django 4.2 on 2023-05-16 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0009_delete_article"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArticleMP",
            new_name="Article",
        ),
    ]
