# Generated by Django 4.2 on 2023-05-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_rename_articlemp_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="highlight_serialized",
            field=models.TextField(blank=True),
        ),
    ]
