# Generated by Django 4.2 on 2023-05-29 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_annotation_highlight_serialized"),
    ]

    operations = [
        migrations.RenameField(
            model_name="annotation",
            old_name="highlight_serialized",
            new_name="highlight_serialization",
        ),
    ]
