# Generated by Django 4.2 on 2023-06-02 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_comment_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
