# Generated by Django 4.2 on 2023-06-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_comment_created_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, default=""),
        ),
    ]
