# Generated by Django 4.2 on 2023-06-09 17:41

from django.db import migrations
from slugify import slugify


def initialize_slug(apps, schema_editor):
    Article = apps.get_model("core", "Article")
    for article in Article.objects.all():
        article.slug = slugify(article.title)
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_article_slug"),
    ]

    operations = [migrations.RunPython(initialize_slug)]
