# Generated by Django 4.2 on 2023-06-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_initialize_slugs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="slug",
        ),
        migrations.AddField(
            model_name="article",
            name="slug_section",
            field=models.SlugField(default=""),
        ),
    ]
