# Generated by Django 4.2 on 2023-06-09 18:47

from django.db import migrations
from slugify import slugify


def initialize_slug_section(apps, schema_editor):
    Article = apps.get_model("core", "Article")
    for article in Article.objects.all():
        article.slug_section = slugify(article.title)
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_article_slug_article_slug_section"),
    ]

    operations = [migrations.RunPython(initialize_slug_section)]
