# Generated by Django 4.2 on 2023-06-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_auto_20230609_1847"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug_full",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug_section",
            field=models.TextField(max_length=50),
        ),
    ]
