# Generated by Django 4.2 on 2023-06-09 18:56

from django.db import migrations

# Note that this an anti-pattern for django migrations,
# but need it for .get_ancestors().
from core.models import Article


def initialize_slug_full(apps, schema_editor):
    """Initialize slug_full field by looping through ancestors."""
    for article in Article.objects.all():
        slugs = []
        for ancestor in article.get_ancestors():
            slugs.append(ancestor.slug_section)
        slugs.append(article.slug_section)
        article.slug_full = "/".join(slugs)
        article.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_article_slug_full_alter_article_slug_section"),
    ]

    operations = [migrations.RunPython(initialize_slug_full)]
