# Generated by Django 4.2 on 2023-06-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_article_slug_full"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug_full",
            field=models.TextField(db_index=True, max_length=1000, unique=True),
        ),
    ]
