# Generated by Django 4.2 on 2023-06-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_article_slug_full"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
