# Generated by Django 4.2 on 2023-07-04 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="core.article",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="core.article",
            ),
        ),
    ]
