# Generated by Django 4.2 on 2023-06-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                default="hi",
                help_text="Case-sensitive version of username",
                max_length=150,
            ),
            preserve_default=False,
        ),
    ]
