# Generated by Django 4.2 on 2023-06-14 20:46

from django.db import migrations


def set_display_name(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        user.display_name = user.username
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_display_name"),
    ]

    operations = [migrations.RunPython(set_display_name)]
