# Generated by Django 4.2 on 2023-04-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_comment_annotation_commenttree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commenttree",
            name="comment_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Plain-text output from rich-text editor.",
            ),
        ),
    ]
