# Generated by Django 4.2 on 2023-04-17 20:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_migrate_to_commenttree"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="reply_to",
        ),
        migrations.AddField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.article",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="comment_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Plain-text output from rich-text editor.",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="depth",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="numchild",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="comment",
            name="path",
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comment",
            name="annotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments_tree",
                to="core.annotation",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_html",
            field=models.TextField(
                blank=True, help_text="HTML output from rich-text editor."
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_json",
            field=models.JSONField(
                blank=True, help_text="JSON output from rich-text editor.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="created_on",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.DeleteModel(
            name="CommentTree",
        ),
    ]
